# controller_manager:
#   ros__parameters:
#     update_rate: 10  # Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster


# bicycle_steering_controller:
#   ros__parameters:
#     type: bicycle_steering_controller/BicycleSteeringController

#     traction_joints_names: ['virtual_rear_wheel_joint']
#     steering_joints_names: ['virtual_front_wheel_joint']
#     wheelbase: 0.325
#     traction_wheel_radius: 0.05

#     reference_timeout: 2.0

#     open_loop: false
#     position_feedback: false
#     velocity_rolling_window_size: 10
#     base_frame_id: base_link
#     odom_frame_id: odom
#     enable_odom_tf: true
#     twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
#     pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]



# controller_manager:
#   ros__parameters:
#     update_rate: 50

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# diff_drive_controller:
#   ros__parameters:
#     type: diff_drive_controller/DiffDriveController

#     left_joints:
#       - front_left_wheel_joint
#       - back_left_wheel_joint
#     right_joints:
#       - front_right_wheel_joint
#       - back_right_wheel_joint

#     wheel_separation: 0.55
#     wheel_radius: 0.1

#     base_frame_id: base_link
#     odom_frame_id: odom
#     publish_rate: 50
#     cmd_vel_timeout: 0.25
